#pragma once

const char INDEX_HTML[] PROGMEM = R"HTML(
<!doctype html><html lang="de"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>ClubIQ RFID-Leser</title><style>
:root{font-family:system-ui,sans-serif;color-scheme:dark;--a:#31d0aa;--bg:#0e1420;--card:#192334;--muted:#aab8cb;--warn:#efb74f}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:#edf4ff}main{max-width:720px;margin:auto;padding:16px}
h1{font-size:clamp(1.45rem,6vw,2.15rem);margin:.3rem 0}.hero{display:flex;align-items:center;justify-content:space-between;gap:10px}.pill{padding:7px 11px;border-radius:99px;background:#173d35;color:#8ff5d8;font-size:.86rem}
.card{background:var(--card);padding:18px;border-radius:16px;margin:14px 0;box-shadow:0 8px 24px #0004}.intro{color:var(--muted);line-height:1.5}
.steps{display:grid;grid-template-columns:repeat(3,1fr);gap:7px;margin:16px 0}.step{border:1px solid #3c4d66;border-radius:10px;padding:10px;font-size:.78rem;color:var(--muted)}.step b{display:block;color:#fff;font-size:1rem}.step.active{border-color:var(--a);background:#173c35}.step.done{border-color:#4d806e;color:#8ff5d8}
.grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}@media(max-width:580px){.grid{grid-template-columns:1fr}.steps{grid-template-columns:1fr}.step{display:flex;gap:8px;align-items:center}.step b{display:inline}}
label{display:block;color:#c0cce0;font-size:.9rem;margin:10px 0 5px}input,select,button,textarea{width:100%;font:inherit;border-radius:10px;border:1px solid #465671;padding:12px;background:#0f1826;color:#fff}input[type=file]{padding:9px}
button{border:0;background:var(--a);color:#05251d;font-weight:800;cursor:pointer;margin-top:10px}button:disabled{opacity:.5;cursor:wait}.secondary{background:#35445c;color:#fff}.danger{background:#733d48;color:#fff}.main-action{padding:15px;font-size:1.05rem}
pre{white-space:pre-wrap;word-break:break-word;background:#0a111c;padding:12px;border-radius:10px;min-height:45px;color:#dce7f7}.hint{color:var(--muted);font-size:.86rem;line-height:1.45}.warning{border-left:4px solid var(--warn);padding-left:10px}.success{color:#8ff5d8}
details.card>summary{cursor:pointer;font-weight:800;font-size:1.05rem}details.card[open]>summary{margin-bottom:12px}.advanced-section{border-top:1px solid #35445c;margin-top:18px;padding-top:14px}
</style></head><body><main>
<div class="hero"><div><small class="hint">CLUBIQ LEDGER</small><h1>RFID-Leser verbinden</h1></div><span class="pill" id="state">wird geladen</span></div>

<section class="card" id="setupCard"><p class="intro">Nur WLAN, Kennwort und die heruntergeladene Zertifikatsdatei auswählen. Den Rest erledigt der Leser automatisch.</p>
<div class="steps"><div class="step active" id="step1"><b>1</b> WLAN wählen</div><div class="step" id="step2"><b>2</b> Sicher verbinden</div><div class="step" id="step3"><b>3</b> Code bestätigen</div></div>
<label>Vereins-WLAN</label><div class="grid"><input id="wifiSsid" list="wifiNetworks" maxlength="32" autocomplete="off" placeholder="WLAN auswählen"><button class="secondary" onclick="scanWifi()">WLANs suchen</button></div><datalist id="wifiNetworks"></datalist>
<label>WLAN-Kennwort</label><input id="wifiPassword" type="password" maxlength="63" autocomplete="new-password" placeholder="Kennwort eingeben">
<label>ClubIQ-Zertifikatsdatei</label><input id="certificateFile" type="file" accept=".crt,.pem,application/x-x509-ca-cert">
<p class="hint warning">Die Datei vorher im Vereins-WLAN unter <b>http://vereinskasse.local:8080/vereinskasse-ca.crt</b> herunterladen. Es ist kein Kopieren des Zertifikatstexts mehr nötig.</p>
<button class="main-action" id="setupButton" onclick="setupReader()">Leser verbinden</button>
<pre id="setupOut">Status wird geprüft …</pre></section>

<section class="card"><h2>Status</h2><div class="grid"><div><small class="hint">Vereins-WLAN</small><p id="wifiState">wird geladen</p></div><div><small class="hint">ClubIQ</small><p id="pushState">wird geladen</p></div></div><pre id="syncMessage">Noch keine Statusmeldung.</pre></section>

<details class="card" id="advanced"><summary>Erweiterte Einstellungen und Kartentest</summary>
<div class="advanced-section"><h3>LED-Statusstreifen</h3><p id="ledHardware">5 LEDs an D8 / GPIO 15</p><button onclick="testLeds()">Alle 5 LEDs testen</button><pre id="ledOut">Bereit.</pre></div>
<div class="advanced-section"><h3>Vereins-WLAN</h3><button class="danger" onclick="deleteWifi()">Gespeichertes WLAN entfernen</button><pre id="wifiOut">Keine Änderung.</pre></div>
<div class="advanced-section"><h3>Kassenserver</h3><label>Adresse der RFID-Schnittstelle</label><input id="serverUrl" maxlength="192" value="https://vereinskasse.local/api/rfid"><label>Root-CA-Zertifikat (PEM)</label><textarea id="rootCa" rows="7" maxlength="2048" spellcheck="false"></textarea><details><summary>Notfallweg: Geräte-Token von Hand eintragen</summary><label>Geräte-Token</label><input id="deviceToken" type="password" maxlength="160" autocomplete="new-password"></details><div class="grid"><button onclick="saveServer()">Server speichern</button><button class="secondary" onclick="testServer()">Verbindung testen</button></div><button class="secondary" onclick="startPairing()">Kopplung erneut starten</button><pre id="serverOut">Noch nicht geladen.</pre></div>
<div class="advanced-section"><h3>Karte testen</h3><button onclick="uid()">UID lesen</button><pre id="uid">Noch keine Karte gelesen.</pre><div class="grid"><div><label>Blocknummer</label><input id="block" type="number" min="0" max="255" value="4"></div><div><label>Authentifizierung</label><select id="kt"><option value="A">Key A</option><option value="B">Key B</option></select></div></div><label>Schlüssel (6 Byte Hex)</label><input id="key" maxlength="12" value="FFFFFFFFFFFF"><button onclick="readBlock()">Block lesen</button><label>Schreibformat</label><select id="fmt"><option value="hex">Hex verwenden</option><option value="text">Text verwenden</option></select><label>Hex (32 Zeichen)</label><textarea id="hex" rows="2"></textarea><label>Text (max. 16 UTF-8-Byte)</label><input id="txt" maxlength="16"><label>Sicherheitsbestätigung</label><input id="confirm" placeholder="SCHREIBEN eingeben"><button class="danger" onclick="writeBlock()">Block schreiben und prüfen</button><pre id="out">Bereit.</pre></div>
</details>
</main><script>
const $=id=>document.getElementById(id),state=$('state');let csrf='',readerCertificate='',setupRunning=false,serverLoaded=false;
async function call(path,data,method){state.textContent='arbeitet…';let options={method:method||(data?'POST':'GET'),headers:{}};if(data){options.headers['Content-Type']='application/x-www-form-urlencoded';options.body=new URLSearchParams(data)}let response=await fetch(path,options),json=await response.json();if(!response.ok)throw Error(json.error||'HTTP '+response.status);state.textContent='bereit';return json}
function setSetupStep(number){for(let i=1;i<=3;i++){let node=$('step'+i);node.classList.toggle('done',i<number);node.classList.toggle('active',i===number)}}
function delay(ms){return new Promise(resolve=>setTimeout(resolve,ms))}
async function status(){let response=await fetch('/api/status',{cache:'no-store'});if(!response.ok)throw Error('Status nicht erreichbar');return response.json()}
async function waitFor(check,message,timeout=60000){const started=Date.now();while(Date.now()-started<timeout){let current=await status();csrf=current.csrf||csrf;if(check(current))return current;$('setupOut').textContent=message;await delay(900)}throw Error('Zeitüberschreitung. WLAN und Raspberry bitte prüfen.')}
$('certificateFile').addEventListener('change',async event=>{let file=event.target.files&&event.target.files[0];readerCertificate=file?await file.text():'';if(readerCertificate&&!readerCertificate.includes('BEGIN CERTIFICATE')){$('setupOut').textContent='Die ausgewählte Datei enthält kein PEM-Zertifikat.';readerCertificate=''}else if(readerCertificate)$('setupOut').textContent='Zertifikat geladen. Jetzt „Leser verbinden“ drücken.'});
async function scanWifi(){try{$('setupOut').textContent='WLANs werden gesucht …';let result;for(let i=0;i<24;i++){result=await call('/api/wifi/scan');if(!result.scanning)break;await delay(250)}if(!result||result.scanning)throw Error('WLAN-Suche dauert zu lange.');let list=$('wifiNetworks');list.innerHTML='';result.networks.forEach(network=>{let option=document.createElement('option');option.value=network.ssid;option.label=`${network.rssi} dBm${network.secure?' · geschützt':' · offen'}`;list.appendChild(option)});$('setupOut').textContent=`${result.networks.length} WLANs gefunden.`}catch(error){$('setupOut').textContent='WLAN-Suche fehlgeschlagen: '+error.message}}
async function setupReader(){if(setupRunning)return;let ssid=$('wifiSsid').value.trim(),password=$('wifiPassword').value;if(!ssid){$('setupOut').textContent='Bitte das Vereins-WLAN auswählen.';return}if(!readerCertificate){$('setupOut').textContent='Bitte zuerst die ClubIQ-Zertifikatsdatei auswählen.';return}setupRunning=true;$('setupButton').disabled=true;try{if(!csrf){let current=await status();csrf=current.csrf||''}setSetupStep(1);$('setupOut').textContent='WLAN wird gespeichert …';await call('/api/wifi',{ssid,password,_csrf:csrf,confirm:'SPEICHERN'});$('wifiPassword').value='';setSetupStep(2);await waitFor(value=>value.stationConnected,'Der Leser verbindet sich mit dem Vereins-WLAN …',45000);$('setupOut').textContent='Sichere ClubIQ-Verbindung wird eingerichtet …';await call('/api/server',{apiUrl:'https://vereinskasse.local/api/rfid',deviceToken:'',rootCa:readerCertificate,_csrf:csrf,confirm:'VERBINDEN'});await waitFor(value=>value.clockReady,'Sichere Uhrzeit wird geladen …',60000);setSetupStep(3);let pairing=await call('/api/pair/start',{_csrf:csrf,confirm:'KOPPELN'});$('setupOut').textContent=`Kopplungscode: ${pairing.code}\n\nTablet wieder mit dem Vereins-WLAN verbinden und diesen Code in ClubIQ bestätigen.`;state.textContent='Code bereit'}catch(error){state.textContent='Fehler';$('setupOut').textContent='Einrichtung nicht abgeschlossen: '+error.message}finally{setupRunning=false;$('setupButton').disabled=false}}
async function refreshStatus(){try{let j=await status();csrf=j.csrf||csrf;if(document.activeElement!==$('wifiSsid'))$('wifiSsid').value=j.stationSsid||$('wifiSsid').value;$('wifiState').textContent=j.stationConnected?`Verbunden: ${j.stationSsid} · ${j.stationIp}`:(j.stationConfigured?`${j.stationSsid} · nicht verbunden`:'Noch nicht eingerichtet');$('pushState').textContent=j.pushConfigured?(j.clockReady?'Bereit':'Warte auf sichere Uhrzeit'):'Noch nicht gekoppelt';$('ledHardware').textContent=`${j.ledCount||5} LEDs an ${j.ledPin||'D8 / GPIO 15'}`;$('syncMessage').textContent=`Firmware ${j.firmwareVersion||'?'}\n${j.message||''}${j.lastUid?`\nLetzte UID: ${j.lastUid}`:''}`;if(j.pairingState==='pending'){$('setupOut').textContent=`Kopplungscode: ${j.pairingCode}\n\nDiesen Code jetzt in ClubIQ bestätigen.`;setSetupStep(3)}else if(j.pairingState==='approved'){$('setupOut').textContent='✓ Leser ist sicher mit ClubIQ verbunden.';setSetupStep(4)}state.textContent='bereit'}catch{state.textContent='offline'}}
async function loadServer(){if(serverLoaded)return;serverLoaded=true;try{let j=await call('/api/server');$('serverUrl').value=j.apiUrl||'https://vereinskasse.local/api/rfid';$('rootCa').value=j.rootCa||'';$('deviceToken').placeholder=j.deviceTokenConfigured?'Token gespeichert – leer lassen':'Geräte-Token';$('serverOut').textContent=j.stored?'Serverdaten sind gespeichert.':'Noch keine Serverdaten gespeichert.'}catch(error){$('serverOut').textContent=error.message}}
$('advanced').addEventListener('toggle',()=>{if($('advanced').open)loadServer()});
async function saveServer(){try{let apiUrl=$('serverUrl').value.trim(),rootCa=$('rootCa').value.trim();if(!rootCa)throw Error('Root-CA fehlt.');let j=await call('/api/server',{apiUrl,deviceToken:$('deviceToken').value,rootCa,_csrf:csrf,confirm:'VERBINDEN'});$('deviceToken').value='';$('serverOut').textContent='✓ '+j.apiUrl+' gespeichert.'}catch(error){$('serverOut').textContent=error.message}}
async function testServer(){try{let j=await call('/api/server/test',{_csrf:csrf,confirm:'TESTEN'});$('serverOut').textContent=`✓ Kassenserver erreichbar (HTTP ${j.status}).`}catch(error){$('serverOut').textContent=error.message}}
async function startPairing(){try{let j=await call('/api/pair/start',{_csrf:csrf,confirm:'KOPPELN'});$('serverOut').textContent=`Kopplungscode: ${j.code}`}catch(error){$('serverOut').textContent=error.message}}
async function deleteWifi(){if(!confirm('Gespeichertes Vereins-WLAN wirklich entfernen?'))return;try{await call('/api/wifi',{_csrf:csrf,confirm:'LOESCHEN'},'DELETE');$('wifiOut').textContent='✓ WLAN entfernt.'}catch(error){$('wifiOut').textContent=error.message}}
async function testLeds(){try{let j=await call('/api/led-test',{_csrf:csrf,confirm:'TESTEN'});$('ledOut').textContent=`Test läuft: ${j.count} LEDs an ${j.pin}.`}catch(error){$('ledOut').textContent=error.message}}
function common(){return{block:$('block').value,key:$('key').value,keyType:$('kt').value}}
async function uid(){try{let j=await call('/api/uid');$('uid').textContent=`UID: ${j.uid}\nTyp: ${j.type}\nGröße: ${j.blocks||'unbekannt'} Blöcke`}catch(error){$('uid').textContent=error.message}}
async function readBlock(){try{let j=await call('/api/read',common());$('hex').value=j.hex;$('txt').value=j.text;$('out').textContent=`Block ${j.block} gelesen.\nUID: ${j.uid}`}catch(error){$('out').textContent=error.message}}
async function writeBlock(){try{let data=common();data.format=$('fmt').value;data.hex=$('hex').value;data.text=$('txt').value;data.confirm=$('confirm').value;let j=await call('/api/write',data);$('out').textContent=`Block ${j.block} geschrieben und verifiziert.\n${j.hex}`;$('confirm').value=''}catch(error){$('out').textContent=error.message}}
refreshStatus();setInterval(()=>{if(!setupRunning)refreshStatus()},8000);
</script></body></html>
)HTML";
