import { env } from "cloudflare:workers";
import { requireRole } from "../session";

export async function GET(){
 const shift=await env.DB.prepare("SELECT * FROM shifts WHERE status='open' ORDER BY opened_at DESC LIMIT 1").first();
 const accounts=await env.DB.prepare("SELECT member_id as memberId,member_name as memberName,ROUND(SUM(amount),2) as balance,CASE WHEN member_id LIKE 'GAST-%' THEN 'guest' ELSE 'member' END as accountType FROM account_transactions GROUP BY member_id,member_name HAVING ROUND(SUM(amount),2) > 0 ORDER BY accountType DESC,member_name").all();
 const recent=await env.DB.prepare("SELECT s.*,r.id as reversal_id,r.reason as reversal_reason FROM sales s LEFT JOIN reversals r ON r.sale_id=s.id ORDER BY s.time DESC LIMIT 20").all();
 const accountEntries=await env.DB.prepare("SELECT at.id,at.member_id as memberId,at.member_name as memberName,at.sale_id as saleId,at.type,at.amount,at.note,at.created_at as createdAt,s.cart_json as cartJson FROM account_transactions at LEFT JOIN sales s ON s.id=at.sale_id ORDER BY at.created_at DESC LIMIT 1000").all();
 const accountItems=await env.DB.prepare("SELECT at.member_id as memberId,si.sale_id as saleId,si.product_name as productName,si.quantity,si.unit_price as unitPrice,si.total FROM account_transactions at JOIN sale_items si ON si.sale_id=at.sale_id WHERE at.amount>0 ORDER BY at.created_at DESC").all();
 return Response.json({shift,accounts:accounts.results,recent:recent.results,accountEntries:accountEntries.results,accountItems:accountItems.results});
}
export async function POST(request:Request){
 try{const b=await request.json() as {action:string;operatorId:string;openingCash?:number;countedCash?:number;saleId?:string;reason?:string;memberId?:string;memberName?:string;amount?:number;paymentMethod?:string;tendered?:number};const op=await requireRole(request,["Kassendienst","Vorstand"]);if(!op)return Response.json({error:"Keine Berechtigung"},{status:403});const now=new Date().toISOString();
 if(b.action==="open"){const active=await env.DB.prepare("SELECT id FROM shifts WHERE status='open'").first();if(active)return Response.json({error:"Es ist bereits eine Kasse geöffnet"},{status:409});const id=crypto.randomUUID();await env.DB.prepare("INSERT INTO shifts (id,opened_by,opened_by_name,opened_at,opening_cash,status) VALUES (?,?,?,?,?,'open')").bind(id,op.id,op.name,now,Number(b.openingCash||0)).run();return Response.json({ok:true})}
 if(b.action==="close"){const sh=await env.DB.prepare("SELECT * FROM shifts WHERE status='open' ORDER BY opened_at DESC LIMIT 1").first<{id:string;opening_cash:number;opened_at:string}>();if(!sh)return Response.json({error:"Keine offene Kasse"},{status:409});const cash=await env.DB.prepare("SELECT COALESCE(SUM(total),0) total FROM sales WHERE method='Bar' AND time>=?").bind(sh.opened_at).first<{total:number}>();const rev=await env.DB.prepare("SELECT COALESCE(SUM(r.amount),0) total FROM reversals r JOIN sales s ON s.id=r.sale_id WHERE s.method='Bar' AND r.created_at>=?").bind(sh.opened_at).first<{total:number}>();const expected=sh.opening_cash+Number(cash?.total||0)-Number(rev?.total||0),counted=Number(b.countedCash||0);await env.DB.prepare("UPDATE shifts SET closed_by=?,closed_at=?,expected_cash=?,counted_cash=?,difference=?,status='closed' WHERE id=?").bind(op.id,now,expected,counted,counted-expected,sh.id).run();await env.BACKUPS.put(`closings/${now.slice(0,10)}/${sh.id}.json`,JSON.stringify({shiftId:sh.id,expected,counted,difference:counted-expected,closedBy:op,closedAt:now}));return Response.json({ok:true,expected,difference:counted-expected})}
 if(b.action==="reverse"){if(op.role!=="Vorstand")return Response.json({error:"Storno nur durch Vorstand"},{status:403});const sale=await env.DB.prepare("SELECT id,total FROM sales WHERE id=?").bind(b.saleId).first<{id:string;total:number}>();if(!sale)return Response.json({error:"Buchung nicht gefunden"},{status:404});if(await env.DB.prepare("SELECT id FROM reversals WHERE sale_id=?").bind(sale.id).first())return Response.json({error:"Bereits storniert"},{status:409});const id=crypto.randomUUID();const allocations=await env.DB.prepare("SELECT * FROM sale_allocations WHERE sale_id=?").bind(sale.id).all<{member_id:string;member_name:string;amount:number}>();const statements=[env.DB.prepare("INSERT INTO reversals (id,sale_id,reason,amount,operator_id,operator_name,created_at) VALUES (?,?,?,?,?,?,?)").bind(id,sale.id,b.reason||"Korrektur",sale.total,op.id,op.name,now),...allocations.results.map((a,i)=>env.DB.prepare("INSERT INTO account_transactions (id,member_id,member_name,sale_id,type,amount,note,operator_id,created_at) VALUES (?,?,?,?,?,?,?,?,?)").bind(`${id}-${i}`,a.member_id,a.member_name,sale.id,"Storno",-a.amount,b.reason||"Korrektur",op.id,now))];await env.DB.batch(statements);await env.BACKUPS.put(`reversals/${now.slice(0,10)}/${id}.json`,JSON.stringify({id,saleId:sale.id,reason:b.reason,operator:op,createdAt:now}));return Response.json({ok:true})}
 if(b.action==="payment"){if(!b.memberId||!b.amount||b.amount<=0)return Response.json({error:"Ungültige Zahlung"},{status:400});const outstanding=await env.DB.prepare("SELECT ROUND(COALESCE(SUM(amount),0),2) balance FROM account_transactions WHERE member_id=?").bind(b.memberId).first<{balance:number}>();const amount=Math.min(Number(b.amount),Number(outstanding?.balance||0));if(amount<=0)return Response.json({error:"Konto ist bereits ausgeglichen"},{status:409});const method=b.paymentMethod==="Bar"?"Bar":"Sonstige",tendered=method==="Bar"?Number(b.tendered??amount):amount;if(tendered<amount)return Response.json({error:"Erhaltener Betrag ist zu niedrig"},{status:400});const id=crypto.randomUUID(),changeDue=Math.round((tendered-amount)*100)/100;await env.DB.batch([env.DB.prepare("INSERT INTO account_transactions (id,member_id,member_name,type,amount,note,operator_id,created_at) VALUES (?,?,?,?,?,?,?,?)").bind(id,b.memberId,b.memberName||b.memberId,"Zahlung",-amount,`Kontenausgleich ${method}`,op.id,now),env.DB.prepare("INSERT INTO payments (id,member_id,method,amount,tendered,change_due,note,operator_id,created_at) VALUES (?,?,?,?,?,?,?,?,?)").bind(`${id}-payment`,b.memberId,method,amount,tendered,changeDue,"Offene Zeche bezahlt",op.id,now),env.DB.prepare("INSERT INTO audit_logs (id,action,entity_type,entity_id,operator_id,details_json,created_at) VALUES (?,?,?,?,?,?,?)").bind(`${id}-audit`,"ACCOUNT_PAYMENT","member_account",b.memberId,op.id,JSON.stringify({amount,method,tendered,changeDue}),now)]);await env.BACKUPS.put(`payments/${now.slice(0,10)}/${id}.json`,JSON.stringify({id,memberId:b.memberId,memberName:b.memberName,amount,method,tendered,changeDue,operator:op,createdAt:now}));return Response.json({ok:true,amount,changeDue,remaining:Math.max(0,Number(outstanding?.balance||0)-amount)})}
 return Response.json({error:"Unbekannte Aktion"},{status:400});
 }catch(e){return Response.json({error:e instanceof Error?e.message:"Vorgang fehlgeschlagen"},{status:500})}
}
