import { env } from "cloudflare:workers";
import { requireProfile } from "../profile-session";
import { requireRole } from "../session";

export async function GET(request:Request){
  const profile=await requireProfile(request);if(!profile)return Response.json({error:"Profilanmeldung erforderlich"},{status:401});
  const shift=await env.DB.prepare("SELECT * FROM shifts WHERE profile_id=? AND status='open' ORDER BY opened_at DESC LIMIT 1").bind(profile.id).first();
  const accounts=await env.DB.prepare("SELECT member_id memberId,member_name memberName,ROUND(SUM(amount),2) balance,CASE WHEN member_id LIKE 'GAST-%' THEN 'guest' ELSE 'member' END accountType FROM account_transactions WHERE profile_id=? GROUP BY member_id,member_name HAVING ROUND(SUM(amount),2)>0 ORDER BY accountType DESC,memberName").bind(profile.id).all();
  const recent=await env.DB.prepare("SELECT s.*,r.id reversal_id,r.reason reversal_reason FROM sales s LEFT JOIN reversals r ON r.sale_id=s.id WHERE s.profile_id=? ORDER BY s.time DESC LIMIT 20").bind(profile.id).all();
  const accountEntries=await env.DB.prepare("SELECT at.id,at.member_id memberId,at.member_name memberName,at.sale_id saleId,at.type,at.amount,at.note,at.created_at createdAt,s.cart_json cartJson FROM account_transactions at LEFT JOIN sales s ON s.id=at.sale_id WHERE at.profile_id=? ORDER BY at.created_at DESC LIMIT 1000").bind(profile.id).all();
  const accountItems=await env.DB.prepare("SELECT at.member_id memberId,si.sale_id saleId,si.product_name productName,si.quantity,si.unit_price unitPrice,si.total FROM account_transactions at JOIN sale_items si ON si.sale_id=at.sale_id WHERE at.profile_id=? AND at.amount>0 ORDER BY at.created_at DESC").bind(profile.id).all();
  return Response.json({shift,accounts:accounts.results,recent:recent.results,accountEntries:accountEntries.results,accountItems:accountItems.results});
}

export async function POST(request:Request){
  try{
    const body=await request.json() as {action:string;openingCash?:number;countedCash?:number;saleId?:string;reason?:string;memberId?:string;memberName?:string;amount?:number;paymentMethod?:string;tendered?:number};
    const [operator,profile]=await Promise.all([requireRole(request,["Kassendienst","Vorstand"]),requireProfile(request)]);if(!operator||!profile)return Response.json({error:"Keine Berechtigung oder Profilanmeldung abgelaufen"},{status:403});const now=new Date().toISOString();
    if(body.action==="open"){
      if(await env.DB.prepare("SELECT id FROM shifts WHERE profile_id=? AND status='open'").bind(profile.id).first())return Response.json({error:"Für dieses Profil ist bereits eine Kasse geöffnet"},{status:409});
      const id=crypto.randomUUID();await env.DB.prepare("INSERT INTO shifts (id,profile_id,opened_by,opened_by_name,opened_at,opening_cash,status) VALUES (?,?,?,?,?,?,'open')").bind(id,profile.id,operator.id,operator.name,now,Number(body.openingCash||0)).run();return Response.json({ok:true});
    }
    if(body.action==="close"){
      const shift=await env.DB.prepare("SELECT * FROM shifts WHERE profile_id=? AND status='open' ORDER BY opened_at DESC LIMIT 1").bind(profile.id).first<{id:string;opening_cash:number;opened_at:string}>();if(!shift)return Response.json({error:"Keine offene Kasse"},{status:409});
      const cash=await env.DB.prepare("SELECT COALESCE(SUM(total),0) total FROM sales WHERE profile_id=? AND method='Bar' AND time>=?").bind(profile.id,shift.opened_at).first<{total:number}>();const reversals=await env.DB.prepare("SELECT COALESCE(SUM(r.amount),0) total FROM reversals r JOIN sales s ON s.id=r.sale_id WHERE s.profile_id=? AND s.method='Bar' AND r.created_at>=?").bind(profile.id,shift.opened_at).first<{total:number}>();const expected=shift.opening_cash+Number(cash?.total||0)-Number(reversals?.total||0),counted=Number(body.countedCash||0);
      await env.DB.prepare("UPDATE shifts SET closed_by=?,closed_at=?,expected_cash=?,counted_cash=?,difference=?,status='closed' WHERE id=? AND profile_id=?").bind(operator.id,now,expected,counted,counted-expected,shift.id,profile.id).run();await env.BACKUPS.put(`closings/${profile.id}/${now.slice(0,10)}/${shift.id}.json`,JSON.stringify({profile,shiftId:shift.id,expected,counted,difference:counted-expected,closedBy:operator,closedAt:now}));return Response.json({ok:true,expected,difference:counted-expected});
    }
    if(body.action==="reverse"){
      if(operator.role!=="Vorstand")return Response.json({error:"Storno nur durch Vorstand"},{status:403});const sale=await env.DB.prepare("SELECT id,total FROM sales WHERE id=? AND profile_id=?").bind(body.saleId,profile.id).first<{id:string;total:number}>();if(!sale)return Response.json({error:"Buchung nicht gefunden"},{status:404});if(await env.DB.prepare("SELECT id FROM reversals WHERE sale_id=?").bind(sale.id).first())return Response.json({error:"Bereits storniert"},{status:409});const id=crypto.randomUUID();const allocations=await env.DB.prepare("SELECT * FROM sale_allocations WHERE sale_id=?").bind(sale.id).all<{member_id:string;member_name:string;amount:number}>();const statements=[env.DB.prepare("INSERT INTO reversals (id,sale_id,reason,amount,operator_id,operator_name,created_at) VALUES (?,?,?,?,?,?,?)").bind(id,sale.id,body.reason||"Korrektur",sale.total,operator.id,operator.name,now),...allocations.results.map((allocation,index)=>env.DB.prepare("INSERT INTO account_transactions (id,profile_id,member_id,member_name,sale_id,type,amount,note,operator_id,created_at) VALUES (?,?,?,?,?,?,?,?,?,?)").bind(`${id}-${index}`,profile.id,allocation.member_id,allocation.member_name,sale.id,"Storno",-allocation.amount,body.reason||"Korrektur",operator.id,now))];await env.DB.batch(statements);await env.BACKUPS.put(`reversals/${profile.id}/${now.slice(0,10)}/${id}.json`,JSON.stringify({profileId:profile.id,id,saleId:sale.id,reason:body.reason,operator,createdAt:now}));return Response.json({ok:true});
    }
    if(body.action==="payment"){
      if(!body.memberId||!body.amount||body.amount<=0)return Response.json({error:"Ungültige Zahlung"},{status:400});const outstanding=await env.DB.prepare("SELECT ROUND(COALESCE(SUM(amount),0),2) balance FROM account_transactions WHERE profile_id=? AND member_id=?").bind(profile.id,body.memberId).first<{balance:number}>();const amount=Math.min(Number(body.amount),Number(outstanding?.balance||0));if(amount<=0)return Response.json({error:"Konto ist bereits ausgeglichen"},{status:409});const method=body.paymentMethod==="Bar"?"Bar":"Sonstige",tendered=method==="Bar"?Number(body.tendered??amount):amount;if(tendered<amount)return Response.json({error:"Erhaltener Betrag ist zu niedrig"},{status:400});const id=crypto.randomUUID(),changeDue=Math.round((tendered-amount)*100)/100;
      await env.DB.batch([env.DB.prepare("INSERT INTO account_transactions (id,profile_id,member_id,member_name,type,amount,note,operator_id,created_at) VALUES (?,?,?,?,?,?,?,?,?)").bind(id,profile.id,body.memberId,body.memberName||body.memberId,"Zahlung",-amount,`Kontenausgleich ${method}`,operator.id,now),env.DB.prepare("INSERT INTO payments (id,profile_id,member_id,method,amount,tendered,change_due,note,operator_id,created_at) VALUES (?,?,?,?,?,?,?,?,?,?)").bind(`${id}-payment`,profile.id,body.memberId,method,amount,tendered,changeDue,"Offene Zeche bezahlt",operator.id,now),env.DB.prepare("INSERT INTO audit_logs (id,action,entity_type,entity_id,operator_id,details_json,created_at) VALUES (?,?,?,?,?,?,?)").bind(`${id}-audit`,"ACCOUNT_PAYMENT","member_account",body.memberId,operator.id,JSON.stringify({profileId:profile.id,amount,method,tendered,changeDue}),now)]);await env.BACKUPS.put(`payments/${profile.id}/${now.slice(0,10)}/${id}.json`,JSON.stringify({profileId:profile.id,id,memberId:body.memberId,memberName:body.memberName,amount,method,tendered,changeDue,operator,createdAt:now}));return Response.json({ok:true,amount,changeDue,remaining:Math.max(0,Number(outstanding?.balance||0)-amount)});
    }
    return Response.json({error:"Unbekannte Aktion"},{status:400});
  }catch(error){return Response.json({error:error instanceof Error?error.message:"Vorgang fehlgeschlagen"},{status:500})}
}
