import test from "node:test";
import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";

const read=p=>readFile(new URL(`../${p}`,import.meta.url),"utf8");
test("enthält die zentralen Kassenabläufe",async()=>{const page=await read("app/page.tsx");for(const feature of ["CashPaymentDialog","MemberFinder","OpenAccountsDialog","Vertrauensliste","Rückgeld berechnen"])assert.ok(page.includes(feature),`${feature} fehlt`)});
test("schützt privilegierte Serveraktionen mit Sitzungen",async()=>{const [data,control,members]=await Promise.all([read("app/api/data/route.ts"),read("app/api/control/route.ts"),read("app/api/members/route.ts")]);assert.ok(data.includes("requireRole(request"));assert.ok(control.includes("requireRole(request"));assert.ok(members.includes("requireRole(request"))});
test("speichert Zahlungen, Positionen und Prüfprotokoll",async()=>{const schema=await read("db/schema.ts");for(const table of ["sale_items","payments","audit_logs","auth_sessions"])assert.ok(schema.includes(table),`${table} fehlt`)});
test("deaktiviert nicht verbundene PayPal-Zahlungen",async()=>{const page=await read("app/page.tsx");assert.match(page,/PayPal · noch nicht verbunden/);assert.ok(!page.includes("PayPal <span>Demo"))});
test("führt in vier einfachen Schritten durch den Vereinsalltag",async()=>{const page=await read("app/page.tsx");for(const feature of ["operationMode","Vereinsabend","Veranstaltung","Zuerst Mitglied wählen","Schnellzugriff","quickProducts","Weitere Aktionen"])assert.ok(page.includes(feature),`${feature} fehlt`);assert.ok(page.includes('operationMode==="club"&&!billingMember'),"Artikelauswahl ist ohne Mitglied nicht abgesichert")});
test("verwaltet Besucher und Besuchervereine dauerhaft",async()=>{const [page,data,schema,backup]=await Promise.all([read("app/page.tsx"),read("app/api/data/route.ts"),read("db/schema.ts"),read("app/api/backup/route.ts")]);for(const feature of ["GuestFinder","Besucherverein","Anlegen und auswählen"])assert.ok(page.includes(feature),`${feature} fehlt`);assert.ok(schema.includes('guest_accounts'));assert.ok(data.includes('ON CONFLICT(id) DO UPDATE'));assert.ok(backup.includes('guest_accounts'))});
test("trennt Vereinszeche und Mitglieder eines Besuchervereins",async()=>{const [page,data,schema]=await Promise.all([read("app/page.tsx"),read("app/api/data/route.ts"),read("db/schema.ts")]);for(const feature of ["Direkt auf den Verein buchen","Mitglied zu","parentId","parentName"])assert.ok(page.includes(feature),`${feature} fehlt`);assert.ok(schema.includes('parent_id'));assert.ok(data.includes('parent_id'));assert.ok(data.includes("'club',NULL"))});
test("erstellt geschützte Monatsabrechnungen mit Verbrauch",async()=>{const [page,monthly]=await Promise.all([read("app/page.tsx"),read("app/api/monthly/route.ts")]);for(const feature of ["MonthlyBilling","Zechen und Verbrauch","Getrunken und verkauft"])assert.ok(page.includes(feature),`${feature} fehlt`);assert.ok(monthly.includes('requireRole(request'));assert.ok(monthly.includes('Stand Monatsende'));assert.ok(monthly.includes('product_name'));assert.ok(monthly.includes('reversals'))});
test("behält NFC und QR trotz manueller Auswahl bei",async()=>{const page=await read("app/page.tsx");for(const feature of ["NDEFReader","NFC-Leser starten","QR-Code","MemberFinder"])assert.ok(page.includes(feature),`${feature} fehlt`)});
test("behält das echte Branding des SV Barver Darts",async()=>{const [page,layout,migration]=await Promise.all([read("app/page.tsx"),read("app/layout.tsx"),read("drizzle/0010_pretty_random.sql")]);for(const file of [page,layout,migration])assert.ok(file.includes("SV Barver Darts"));assert.ok(page.includes('/sv-barver-darts.png'));assert.ok(!page.includes("SV Beispielhausen"))});
test("trennt Sparten mit sicherer Profil-PIN",async()=>{const [page,session,profiles,data,control,monthly,schema,migration]=await Promise.all([read("app/page.tsx"),read("app/api/profile-session/route.ts"),read("app/api/profiles/route.ts"),read("app/api/data/route.ts"),read("app/api/control/route.ts"),read("app/api/monthly/route.ts"),read("db/schema.ts"),read("drizzle/0010_pretty_random.sql")]);for(const feature of ["ProfileGate","ProfileManager","6-stellige Profil-PIN","Sperre nach fünf Fehlversuchen"])assert.ok(page.includes(feature),`${feature} fehlt`);assert.ok(session.includes("PBKDF2")||await read("app/api/profile-session.ts").then(file=>file.includes("PBKDF2")));assert.ok(session.includes("failed_attempts"));assert.ok(session.includes("Max-Age=43200")||await read("app/api/profile-session.ts").then(file=>file.includes("43200")));assert.ok(profiles.includes("PROFILE_CREATED"));for(const route of [data,control,monthly])assert.ok(route.includes("profile_id"));for(const table of ["profiles","profile_sessions"])assert.ok(schema.includes(table));assert.ok(migration.includes("must_change_pin"));assert.ok(migration.includes("DEFAULT 'darts'"))});
test("ordnet Verkäufe Veranstaltungen zu und erstellt Einkaufsrichtwerte",async()=>{const [page,events,data,schema,migration]=await Promise.all([read("app/page.tsx"),read("app/api/events/route.ts"),read("app/api/data/route.ts"),read("db/schema.ts"),read("drizzle/0009_harsh_viper.sql")]);for(const feature of ["EventAnalytics","Was wurde verbraucht?","Nächstes Mal","active-event-banner"])assert.ok(page.includes(feature),`${feature} fehlt`);assert.ok(events.includes("recommendedQuantity"));assert.ok(events.includes("LEFT JOIN reversals"));assert.ok(events.includes("EVENT_CREATED"));assert.ok(data.includes("event_id"));assert.ok(schema.includes('sqliteTable("events"'));assert.ok(migration.includes("ALTER TABLE `sales` ADD `event_id`"))});
