import test from "node:test";
import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";

const read=p=>readFile(new URL(`../${p}`,import.meta.url),"utf8");
test("enthält die zentralen Kassenabläufe",async()=>{const page=await read("app/page.tsx");for(const feature of ["CashPaymentDialog","MemberFinder","OpenAccountsDialog","Vertrauensliste","Rückgeld berechnen"])assert.ok(page.includes(feature),`${feature} fehlt`)});
test("schützt privilegierte Serveraktionen mit Sitzungen",async()=>{const [data,control,members]=await Promise.all([read("app/api/data/route.ts"),read("app/api/control/route.ts"),read("app/api/members/route.ts")]);assert.ok(data.includes("requireRole(request"));assert.ok(control.includes("requireRole(request"));assert.ok(members.includes("requireRole(request"))});
test("speichert Zahlungen, Positionen und Prüfprotokoll",async()=>{const schema=await read("db/schema.ts");for(const table of ["sale_items","payments","audit_logs","auth_sessions"])assert.ok(schema.includes(table),`${table} fehlt`)});
test("deaktiviert nicht verbundene PayPal-Zahlungen",async()=>{const page=await read("app/page.tsx");assert.match(page,/PayPal · noch nicht verbunden/);assert.ok(!page.includes("PayPal <span>Demo"))});
test("führt in vier einfachen Schritten durch den Vereinsalltag",async()=>{const page=await read("app/page.tsx");for(const feature of ["operationMode","Vereinsabend","Veranstaltung","Zuerst Mitglied wählen","Schnellzugriff","quickProducts","Weitere Aktionen"])assert.ok(page.includes(feature),`${feature} fehlt`);assert.ok(page.includes('operationMode==="club"&&!billingMember'),"Artikelauswahl ist ohne Mitglied nicht abgesichert")});
test("verwaltet Besucher und Besuchervereine dauerhaft",async()=>{const [page,data,schema,backup]=await Promise.all([read("app/page.tsx"),read("app/api/data/route.ts"),read("db/schema.ts"),read("app/api/backup/route.ts")]);for(const feature of ["GuestFinder","Besucherverein","Anlegen und auswählen"])assert.ok(page.includes(feature),`${feature} fehlt`);assert.ok(schema.includes('guest_accounts'));assert.ok(data.includes('ON CONFLICT(id) DO UPDATE'));assert.ok(backup.includes('guest_accounts'))});
test("trennt Vereinszeche und Mitglieder eines Besuchervereins",async()=>{const [page,data,schema]=await Promise.all([read("app/page.tsx"),read("app/api/data/route.ts"),read("db/schema.ts")]);for(const feature of ["Direkt auf den Verein buchen","Mitglied zu","parentId","parentName"])assert.ok(page.includes(feature),`${feature} fehlt`);assert.ok(schema.includes('parent_id'));assert.ok(data.includes('parent_id'));assert.ok(data.includes("'club',NULL"))});
