import React,{useEffect,useState} from 'react';

export function useEmailLink(){
  function read(){const params=new URLSearchParams(location.hash.slice(1));for(const stage of ['current','new']){const token=params.get(`email-${stage}`);if(token){history.replaceState(null,'',location.pathname);return {stage,token};}}return null;}
  const[link,setLink]=useState(read);
  useEffect(()=>{const changed=()=>{const next=read();if(next)setLink(next);};addEventListener('hashchange',changed);return()=>removeEventListener('hashchange',changed);},[]);
  return [link,setLink];
}
export function ChangeEmail({api,user,onDone}){
  const[error,setError]=useState(''),[busy,setBusy]=useState(false);
  async function submit(e){e.preventDefault();const values=Object.fromEntries(new FormData(e.currentTarget));setError('');if(values.newEmail.trim().toLowerCase()!==values.repeat.trim().toLowerCase()){setError('Die beiden E-Mail-Adressen stimmen nicht überein.');return;}setBusy(true);try{const result=await api('/api/account/email',{newEmail:values.newEmail.trim(),password:values.password});onDone(result.message);}catch(e){setError(e.message);}finally{setBusy(false);}}
  return <form onSubmit={submit}><p>Aktuell: <b>{user.email}</b></p><ol className="help-list"><li>Neue Adresse eintragen und mit deinem aktuellen Passwort bestätigen.</li><li>Den ersten Link im <b>bisherigen</b> Postfach öffnen.</li><li>Danach den zweiten Link im <b>neuen</b> Postfach bestätigen.</li></ol><p className="small">Beide Links gelten jeweils 15 Minuten. Dein Passwort und dein zweiter Faktor bleiben bestehen. Nach dem Wechsel meldest du dich mit der neuen Adresse neu an.</p>{error&&<p className="notice error" role="alert">{error}</p>}<label className="field"><span>Neue E-Mail-Adresse</span><input type="email" name="newEmail" required maxLength={254} autoComplete="email"/></label><label className="field"><span>Neue E-Mail-Adresse wiederholen</span><input type="email" name="repeat" required maxLength={254} autoComplete="off"/></label><label className="field"><span>Aktuelles Passwort</span><input type="password" name="password" required maxLength={128} autoComplete="current-password"/></label><p className="notice">Das ändert dein persönliches Verwaltungskonto und dessen Empfängeradresse. Allgemeine Kassenwart-Verteiler für den automatischen Monatsversand bleiben separat auf der Wartungsseite. Das Gmail-Absenderkonto bleibt unverändert.</p>{user.preview&&<p className="small">Im Testsystem: Anschließend unter „Mein Konto → Testpostfach“ beide simulierten Nachrichten öffnen. Es wird keine echte E-Mail versendet.</p>}<button className="primary" disabled={busy}>{busy?'Bitte warten …':'Änderung anfordern'}</button></form>;
}
export function ConfirmEmail({api,link,user,onClose,onDone}){
  const[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
  async function confirm(){setBusy(true);setError('');try{const result=await api('/api/account/email/confirm',link);if(result.signInAgain)onDone(result.message);else setMessage(result.message);}catch(e){setError(e.message);}finally{setBusy(false);}}
  return <main className="narrow"><section className="card"><span className="eyebrow">PERSÖNLICHER ZUGANG · E-MAIL-ÄNDERUNG</span><h1>{link.stage==='current'?'Bisherige Adresse bestätigen':'Neue Adresse bestätigen'}</h1><p>Angemeldet als <b>{user.email}</b>. Bestätige nur eine Änderung, die du selbst angefordert hast.</p>{error&&<p className="notice error" role="alert">{error}</p>}{message?<p className="notice success" role="status">{message}</p>:<><p>{link.stage==='current'?'Damit wird der zweite Bestätigungslink an das neue Postfach gesendet. Deine Anmeldeadresse ändert sich noch nicht.':'Damit wird die neue Anmeldeadresse wirksam. Alle bisherigen Anmeldungen werden beendet; Passwort und zweiter Faktor bleiben unverändert.'}</p><button className="primary" disabled={busy} onClick={confirm}>{busy?'Wird bestätigt …':link.stage==='current'?'Bisherige Adresse bestätigen':'Neue Adresse verbindlich speichern'}</button></>}<button className="secondary" disabled={busy} onClick={onClose}>{message?'Zurück zu Mein Konto':'Abbrechen'}</button></section></main>;
}
// Only the loopback fixture implements this API; no production mailbox/debug route.
export function TestMailbox({api}){
  const[messages,setMessages]=useState([]),[error,setError]=useState('');
  async function load(){try{setMessages((await api('/api/demo/mailbox')).messages);setError('');}catch(e){setError(e.message);}}
  useEffect(()=>{let active=true;api('/api/demo/mailbox').then(r=>{if(active)setMessages(r.messages);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[api]);
  return <section className="card"><div className="section-head"><h2>Testpostfach</h2><button className="secondary" onClick={load}>Testpostfach aktualisieren</button></div><p>Nur lokal simulierte Bestätigungen deines Testkontos. Es wird nichts an echte Postfächer gesendet.</p>{error&&<p className="notice error" role="alert">{error}</p>}{messages.length?<ul className="history">{messages.map(m=><li key={m.id}><div><b>{m.subject}</b><small>An: {m.recipient}</small><small>{new Date(m.created_at).toLocaleString('de-DE')}</small></div><a className="secondary" href={m.url}>Bestätigungslink öffnen</a></li>)}</ul>:<p>Keine offenen Testbestätigungen.</p>}</section>;
}
