import React,{useEffect,useState} from 'react';
import {startLivePolling,editingForm} from '../../app/live-poll.mjs';
import {BarChart,Bar,CartesianGrid,Legend,ResponsiveContainer,Tooltip,XAxis,YAxis} from 'recharts';

const euro=value=>Number(value||0).toLocaleString('de-DE',{style:'currency',currency:'EUR'});
const count=value=>Number(value||0).toLocaleString('de-DE');
const monthLabel=value=>new Date(`${value}-01T12:00:00Z`).toLocaleDateString('de-DE',{month:'short',year:'2-digit'});
function period(months=12){
  const to=new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Berlin',year:'numeric',month:'2-digit'}).format(new Date());
  const date=new Date(`${to}-01T12:00:00Z`);date.setUTCMonth(date.getUTCMonth()-months+1);
  return {from:date.toISOString().slice(0,7),to};
}
function DataTable({title,rows,columns}){
  return <details className="chart-data"><summary>Datentabelle: {title}</summary><div className="table-wrap"><table><thead><tr>{columns.map(c=><th key={c.key}>{c.label}</th>)}</tr></thead><tbody>{rows.map((row,i)=><tr key={i}>{columns.map(c=><td key={c.key}>{c.format?c.format(row[c.key]):row[c.key]}</td>)}</tr>)}</tbody></table></div></details>;
}
function HorizontalChart({rows,field,label,money=false,valueLabel=money?'Umsatz':'Menge'}){
  return <div className="chart" role="group" aria-label={label} style={{height:Math.max(190,rows.length*39)}}><ResponsiveContainer width="100%" height="100%" minWidth={0}>
    <BarChart data={rows} layout="vertical" margin={{left:0,right:20,top:5,bottom:5}} accessibilityLayer>
      <CartesianGrid horizontal={false} stroke="#e5e9df"/><XAxis type="number" tickFormatter={money?v=>`${count(v)} €`:count} tick={{fontSize:10}}/>
      <YAxis dataKey="name" type="category" width={132} tickFormatter={v=>v.length>19?`${v.slice(0,18)}…`:v} tick={{fontSize:11}}/>
      <Tooltip formatter={v=>[money?euro(v):`${count(v)} Stück`,valueLabel]}/><Bar dataKey={field} fill="#285b48" radius={[0,4,4,0]} isAnimationActive={false}/>
    </BarChart>
  </ResponsiveContainer></div>;
}
export function Statistics({api,refresh,onError,onSync,onExpired}){
  const[range,setRange]=useState(()=>period()),[draft,setDraft]=useState(()=>period()),[stats,setStats]=useState(null),[loading,setLoading]=useState(true);
  useEffect(()=>startLivePolling({interval:5000,allowed:()=>!editingForm(),
    load:async signal=>{const value=await api(`/api/manage/statistics?${new URLSearchParams(range)}`,undefined,'GET',signal);if(signal.aborted||editingForm())return false;setStats(value);setLoading(false);},
    onSuccess:()=>onSync({state:'online',at:Date.now()}),
    onError:error=>{setLoading(false);if(error.kind==='cloudflare-access'){onError('');onSync(current=>({...current,state:'access'}));}else if(error.status===401||error.status===403)onExpired();else{onError(error.message);onSync(current=>({...current,state:'offline'}));}}
  }),[api,range,refresh,onError,onSync,onExpired]);
  function choose(value){setDraft(value);setRange(value);setLoading(true);}
  return <>
    <section className="card stats-filter"><form data-live-filter className="actions" onSubmit={event=>{event.preventDefault();choose({...draft});}}><label className="field"><span>Statistik von</span><input type="month" required min="2000-01" max={draft.to} value={draft.from} onChange={event=>setDraft({...draft,from:event.target.value})}/></label><label className="field"><span>Statistik bis</span><input type="month" required min={draft.from} max="2099-12" value={draft.to} onChange={event=>setDraft({...draft,to:event.target.value})}/></label><button className="primary" disabled={loading}>Zeitraum anzeigen</button></form><div className="actions period-buttons">{[3,6,12].map(n=><button key={n} className="secondary" onClick={()=>choose(period(n))}>Letzte {n} Monate</button>)}<button className="secondary" onClick={()=>{const value=period();choose({...value,from:`${value.to.slice(0,4)}-01`});}}>Dieses Jahr</button></div><p className="small">Bis zu 36 Monate. Buchungsmonate wie in der Abrechnung (UTC); Wochentage nach deutscher Ortszeit.</p></section>
    {loading?<p role="status">Statistiken werden geladen …</p>:!stats?<p className="empty">Keine Auswertung verfügbar. Bitte erneut laden.</p>:<>
      <p className="small">Auswertung: {monthLabel(stats.from)} bis {monthLabel(stats.to)} · Stornierte Verkäufe sind ausgeschlossen.</p>
      <div className="metrics stats-metrics"><div><span>Verkaufsumsatz</span><strong>{euro(stats.summary.revenue)}</strong></div><div><span>Verkäufe / Bons</span><strong>{count(stats.summary.sales)}</strong></div><div><span>Durchschnitt je Verkauf</span><strong>{euro(stats.summary.averageSale)}</strong></div><div><span>Verbrauchte Artikel</span><strong>{count(stats.summary.quantity)} <small>Stück</small></strong></div><div><span>Zahlungen auf Konten</span><strong>{euro(stats.summary.payments)}</strong><small>Nicht zum Umsatz addieren</small></div><div><span>Aktuell offene Konten</span><strong>{euro(stats.summary.outstanding)}</strong><small>{count(stats.summary.openAccounts)} Konten · Stand heute</small></div></div>
      {!stats.summary.sales&&<p className="notice">Im gewählten Zeitraum liegen noch keine Verkäufe vor. Die Diagramme zeigen deshalb keine Umsätze; aktuelle Kontosalden werden unabhängig davon ausgewertet.</p>}
      <section className="card"><div className="section-head"><div><span className="eyebrow">ENTWICKLUNG</span><h2>Umsatz & Kontozahlungen</h2></div><span className="badge">Euro pro Monat</span></div><p>Ein Verkauf erzeugt Umsatz. Eine spätere Kontozahlung begleicht eine Forderung – sie ist kein zweiter Verkauf.</p><div className="chart" role="group" aria-label="Diagramm Monatsumsatz und Kontozahlungen"><ResponsiveContainer width="100%" height={285} minWidth={0}><BarChart data={stats.months} margin={{left:0,right:12,top:10,bottom:5}} accessibilityLayer><CartesianGrid vertical={false} stroke="#e5e9df"/><XAxis dataKey="month" tickFormatter={monthLabel} tick={{fontSize:10}} minTickGap={18}/><YAxis tickFormatter={v=>`${count(v)} €`} tick={{fontSize:10}} width={65}/><Tooltip labelFormatter={monthLabel} formatter={euro}/><Legend/><Bar dataKey="revenue" name="Verkaufsumsatz" fill="#285b48" radius={[4,4,0,0]} isAnimationActive={false}/><Bar dataKey="payments" name="Zahlungen auf Konten" fill="#b49655" radius={[4,4,0,0]} isAnimationActive={false}/></BarChart></ResponsiveContainer></div><DataTable title="Monatswerte" rows={stats.months} columns={[{key:'month',label:'Monat',format:monthLabel},{key:'revenue',label:'Umsatz',format:euro},{key:'payments',label:'Kontozahlungen',format:euro},{key:'sales',label:'Verkäufe',format:count}]}/></section>
      <div className="two-col"><section className="card"><span className="eyebrow">SORTIMENT</span><h2>Beliebteste Artikel</h2><p>Bis zu 12 Artikel nach Verbrauch in Stück. Enthaltene Paketartikel zählen mit, die Paket-Hülle nicht nochmals.</p>{stats.products.length?<HorizontalChart rows={stats.products} field="quantity" label="Diagramm beliebteste Artikel"/>:<p className="empty">Noch kein Artikelverbrauch.</p>}<DataTable title="Artikelmengen" rows={stats.products} columns={[{key:'name',label:'Artikel'},{key:'quantity',label:'Stück',format:count}]}/></section><section className="card"><span className="eyebrow">UMSATZVERTEILUNG</span><h2>Umsatz nach Kategorie</h2><p>Die 8 größten Kategorien. Es gilt die heutige Artikelzuordnung; frühere Preise bleiben erhalten. Gelöschte Artikel: „Nicht zugeordnet“.</p>{stats.categories.length?<HorizontalChart rows={stats.categories.slice(0,8)} field="revenue" label="Diagramm Kategorieumsatz" money/>:<p className="empty">Noch keine Kategorieumsätze.</p>}<DataTable title="Alle Kategorien" rows={stats.categories} columns={[{key:'name',label:'Kategorie'},{key:'revenue',label:'Umsatz',format:euro}]}/></section></div>
      <div className="two-col"><section className="card"><span className="eyebrow">VEREINSBETRIEB</span><h2>Welche Tage sind stark?</h2><p>Umsatz je Wochentag über den gewählten Zeitraum, nicht der Tagesdurchschnitt.</p><div className="chart" role="group" aria-label="Diagramm Umsatz nach Wochentag"><ResponsiveContainer width="100%" height={250} minWidth={0}><BarChart data={stats.weekdays} accessibilityLayer><CartesianGrid vertical={false} stroke="#e5e9df"/><XAxis dataKey="name" tick={{fontSize:11}}/><YAxis width={60} tick={{fontSize:10}} tickFormatter={v=>`${count(v)} €`}/><Tooltip formatter={v=>[euro(v),'Umsatz']}/><Bar dataKey="revenue" fill="#718367" radius={[4,4,0,0]} isAnimationActive={false}/></BarChart></ResponsiveContainer></div><DataTable title="Wochentage" rows={stats.weekdays} columns={[{key:'name',label:'Tag'},{key:'revenue',label:'Umsatz',format:euro},{key:'sales',label:'Verkäufe',format:count}]}/></section><section className="card"><span className="eyebrow">KONTOSTÄNDE · UNABHÄNGIG VOM ZEITRAUM</span><h2>Offene Beträge heute</h2><p>Summe offener Einzelkonten nach Saldenhöhe. Guthaben separat: <b>{euro(stats.summary.credits)}</b>. Keine Aussage zur Überfälligkeit.</p><HorizontalChart rows={stats.balances.map(b=>({...b,name:`${b.name} (${b.count})`}))} field="amount" label="Diagramm aktuell offene Kontobeträge" money valueLabel="Offener Betrag"/><DataTable title="Aktuelle Salden" rows={stats.balances} columns={[{key:'name',label:'Kontostand'},{key:'count',label:'Konten',format:count},{key:'amount',label:'Offener Betrag',format:euro}]}/></section></div>
      <section className="card"><h2>Verkäufe nach Zahlungsart</h2><p>Beim Verkauf gespeicherte Zahlungsart. Anschreiben / Vertrauensliste ist keine bestätigte Bankzahlung.</p><div className="table-wrap"><table><thead><tr><th>Zahlungsart</th><th>Verkäufe</th><th>Umsatz</th></tr></thead><tbody>{stats.methods.map(row=><tr key={row.name}><td>{row.name}</td><td>{count(row.sales)}</td><td>{euro(row.revenue)}</td></tr>)}</tbody></table></div>{!stats.methods.length&&<p className="empty">Noch keine Verkäufe im Zeitraum.</p>}</section>
    </>}
  </>;
}
