import {createRequire} from 'node:module';
import {mkdir} from 'node:fs/promises';
import {resolve} from 'node:path';
import {createOTP} from '@better-auth/utils/otp';
import {testPassword} from '../tests/auth-fixture.mjs';
import {DatabaseSync} from 'node:sqlite';
import {fileURLToPath} from 'node:url';
// Reset only the explicitly disposable QA identity; preserve the person's demo login/MFA.
const qaDb=new DatabaseSync(fileURLToPath(new URL('../../outputs/backoffice-preview/demo-auth.sqlite',import.meta.url)));
const qaUser=qaDb.prepare("SELECT id FROM bo_user WHERE email IN ('browserqa@example.test','browserqa-updated@example.test')").get();
if(!qaUser)throw new Error('Start the local preview fixture first.');
qaDb.prepare('UPDATE bo_user SET "twoFactorEnabled"=0 WHERE id=?').run(qaUser.id);
qaDb.prepare("UPDATE bo_user SET email='browserqa@example.test' WHERE id=?").run(qaUser.id);
qaDb.prepare('DELETE FROM bo_verification WHERE value=?').run(qaUser.id);
for(const table of ['bo_two_factor','bo_session'])qaDb.prepare(`DELETE FROM ${table} WHERE "userId"=?`).run(qaUser.id);
qaDb.close();
const require=createRequire(import.meta.url);
const {chromium}=require(process.env.PLAYWRIGHT_PATH||'playwright');
const directory=resolve('../outputs/backoffice-qa');await mkdir(directory,{recursive:true});
const browser=await chromium.launch({headless:true,...(process.env.EDGE_PATH?{executablePath:process.env.EDGE_PATH}:{})});
try{
  const context=await browser.newContext({viewport:{width:1440,height:960}}),page=await context.newPage(),errors=[];
  page.on('pageerror',error=>errors.push(error.message));
  await page.goto('http://127.0.0.1:5176/');await page.getByRole('heading',{name:'Willkommen zurück'}).waitFor();
  await page.screenshot({path:resolve(directory,'login.png'),fullPage:true});
  await page.getByRole('button',{name:'Passwort vergessen?'}).click();await page.getByLabel('E-Mail-Adresse').fill('unknown@example.test');
  await page.getByRole('button',{name:'Link anfordern'}).click();await page.getByRole('status').filter({hasText:'Falls für diese E-Mail'}).waitFor();
  await page.getByRole('button',{name:'Zurück zur Anmeldung'}).click();
  await page.getByLabel('E-Mail-Adresse').fill('browserqa@example.test');await page.locator('input[type="password"]').fill(testPassword);
  await page.getByRole('button',{name:'Sicher anmelden'}).click();await page.getByRole('heading',{name:/Ein zweiter Schlüssel/}).waitFor();
  await page.getByText('Noch kein QR-Code zu sehen? Das ist hier normal.',{exact:true}).waitFor();
  await page.screenshot({path:resolve(directory,'setup-help.png'),fullPage:true});
  await page.locator('input[type="password"]').fill(testPassword);
  const response=page.waitForResponse(r=>r.url().endsWith('/two-factor/enable')&&r.request().method()==='POST');
  await page.getByRole('button',{name:'Einrichtung starten'}).click();const setup=await(await response).json();
  const secret=new URL(setup.totpURI).searchParams.get('secret'),alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';let bits='';
  for(const ch of secret.replaceAll('=',''))bits+=alphabet.indexOf(ch).toString(2).padStart(5,'0');
  const bytes=[];for(let i=0;i+8<=bits.length;i+=8)bytes.push(parseInt(bits.slice(i,i+8),2));
  await page.getByRole('checkbox').check();await page.getByLabel('Authenticator-Code').fill(await createOTP(Buffer.from(bytes).toString()).totp());
  await page.getByRole('button',{name:'Einrichtung bestätigen'}).click();await page.getByRole('heading',{name:'Übersicht',exact:true}).waitFor();
  await page.getByText('203,00 €',{exact:true}).first().waitFor();await page.screenshot({path:resolve(directory,'dashboard.png'),fullPage:true});
  await page.getByRole('navigation').getByRole('button',{name:'Abrechnungen',exact:true}).click();
  await page.getByRole('row').filter({hasText:'Alex Beispiel'}).getByRole('button',{name:'Details',exact:true}).click();await page.getByRole('heading',{name:'Alex Beispiel'}).waitFor();
  await page.getByRole('button',{name:'Überweisung erfassen'}).click();await page.getByRole('dialog').waitFor();
  await page.screenshot({path:resolve(directory,'invoice.png'),fullPage:true});await page.getByRole('button',{name:'Abbrechen',exact:true}).click();
  await page.getByRole('button',{name:'Abrechnung per E-Mail',exact:true}).click();
  await page.getByRole('checkbox',{name:/kassenwart@example.test/}).check();
  await page.screenshot({path:resolve(directory,'mail-recipients.png'),fullPage:true});
  await page.getByRole('checkbox',{name:/Ich habe Monat und/}).check();
  await page.getByRole('button',{name:'Testversand simulieren',exact:true}).click();
  await page.getByRole('status').filter({hasText:/Abrechnung für 2 Empfänger/}).waitFor();
  await page.getByRole('navigation').getByRole('button',{name:'Artikel & Preise',exact:true}).click();
  await page.getByRole('button',{name:'Artikel hinzufügen',exact:true}).click();
  const productName=`QA-Testartikel ${Date.now()}`;
  await page.getByLabel('Artikelname',{exact:true}).fill(productName);
  await page.getByLabel('Kategorie',{exact:true}).fill('Testsortiment');
  await page.getByLabel('Normalpreis (€)',{exact:true}).fill('3,50');
  await page.getByLabel('Mitgliederpreis (€), leer = Normalpreis',{exact:true}).fill('2,50');
  await page.getByRole('button',{name:'Artikel anlegen',exact:true}).click();
  await page.getByText(productName,{exact:true}).waitFor();
  // Independent browser view + authenticated API write simulate a second operator.
  const observer=await page.context().newPage();await observer.goto('http://127.0.0.1:5176/');
  await observer.getByRole('navigation').getByRole('button',{name:'Artikel & Preise',exact:true}).click();
  await observer.getByRole('row').filter({hasText:productName}).getByRole('button',{name:'Bearbeiten',exact:true}).click();
  const draftName='Nicht gespeicherter Testentwurf';
  await observer.getByLabel('Artikelname',{exact:true}).fill(draftName);
  async function renameQaProduct(name){
    const list=await(await page.request.get('http://127.0.0.1:5176/api/manage/products')).json();
    const product=list.products.find(p=>p.name===productName||p.name===productName+' Live');
    if(!product)throw new Error('QA product missing');
    const result=await page.request.patch(`http://127.0.0.1:5176/api/manage/products/${product.id}`,{headers:{Origin:'http://127.0.0.1:5176'},data:{name,category:product.category,price:String(product.price),memberPrice:String(product.member_price),version:product.updated_at}});
    if(!result.ok())throw new Error('QA update failed: '+await result.text());
  }
  await renameQaProduct(productName+' Live');
  await page.getByText(productName+' Live',{exact:true}).waitFor({timeout:10000});
  if(await observer.getByLabel('Artikelname',{exact:true}).inputValue()!==draftName)throw new Error('Live refresh overwrote an input');
  await observer.getByRole('button',{name:'Verbindlich speichern',exact:true}).click();
  await observer.getByRole('dialog').getByRole('alert').filter({hasText:'Zwischenzeitlich geändert'}).waitFor();
  await observer.getByRole('button',{name:'Abbrechen',exact:true}).click();
  await observer.getByText(productName+' Live',{exact:true}).waitFor({timeout:10000});
  await page.route('**/api/manage/products',route=>route.abort());
  await page.getByRole('status').filter({hasText:'Verbindung unterbrochen'}).waitFor({timeout:10000});
  await renameQaProduct(productName);
  await page.unroute('**/api/manage/products');
  await page.evaluate(()=>window.dispatchEvent(new Event('online')));
  await page.getByText(productName,{exact:true}).waitFor({timeout:10000});
  await page.locator('.live-online').waitFor({timeout:10000});
  await page.screenshot({path:resolve(directory,'live-sync.png'),fullPage:true});await observer.close();
  await page.reload();await page.getByRole('navigation').getByRole('button',{name:'Artikel & Preise',exact:true}).click();
  await page.getByText(productName,{exact:true}).waitFor();
  await page.getByRole('navigation').getByRole('button',{name:'Mitglieder',exact:true}).click();
  await page.getByRole('row').filter({hasText:'Lena Muster'}).waitFor();
  if(await page.getByRole('columnheader',{name:'Rechnungs-E-Mail',exact:true}).count())throw new Error('Member email field should be hidden');
  await page.getByRole('row').filter({hasText:'Lena Muster'}).getByRole('button',{name:'Bearbeiten',exact:true}).click();
  if(await page.getByRole('dialog').locator('input[type="email"]').count())throw new Error('Member editing must not require email');
  await page.getByRole('button',{name:'Abbrechen',exact:true}).click();
  await page.screenshot({path:resolve(directory,'example-members.png'),fullPage:true});
  for(const name of ['Mitglieder','Artikel & Preise','Statistiken','Mein Konto']){
    await page.getByRole('navigation').getByRole('button',{name,exact:true}).click();await page.getByRole('heading',{name,exact:true}).waitFor();
  }
  await page.getByRole('button',{name:'E-Mail-Adresse ändern',exact:true}).click();
  await page.getByLabel('Neue E-Mail-Adresse',{exact:true}).fill('browserqa-updated@example.test');
  await page.getByLabel('Neue E-Mail-Adresse wiederholen',{exact:true}).fill('browserqa-updated@example.test');
  await page.getByLabel('Aktuelles Passwort',{exact:true}).fill(testPassword);
  await page.screenshot({path:resolve(directory,'email-change.png'),fullPage:true});
  await page.getByRole('button',{name:'Änderung anfordern',exact:true}).click();
  await page.getByRole('status').filter({hasText:'Wenn die neue Adresse verfügbar ist'}).waitFor();
  await page.getByRole('button',{name:'Testpostfach aktualisieren',exact:true}).click();
  await page.getByRole('link',{name:'Bestätigungslink öffnen',exact:true}).click();
  await page.getByRole('button',{name:'Bisherige Adresse bestätigen',exact:true}).click();
  await page.getByRole('status').filter({hasText:'Bisherige Adresse bestätigt'}).waitFor();
  await page.getByRole('button',{name:'Zurück zu Mein Konto',exact:true}).click();
  await page.getByRole('link',{name:'Bestätigungslink öffnen',exact:true}).click();
  await page.getByRole('button',{name:'Neue Adresse verbindlich speichern',exact:true}).click();
  await page.getByRole('heading',{name:'Willkommen zurück',exact:true}).waitFor();
  await page.getByRole('status').filter({hasText:'Neue E-Mail-Adresse gespeichert'}).waitFor();
  await page.getByLabel('E-Mail-Adresse',{exact:true}).fill('browserqa-updated@example.test');
  await page.locator('input[type="password"]').fill(testPassword);
  await page.getByRole('button',{name:'Sicher anmelden',exact:true}).click();
  await page.getByRole('button',{name:'Stattdessen Wiederherstellungscode',exact:true}).click();
  await page.getByLabel('Wiederherstellungscode',{exact:true}).fill(setup.backupCodes[0]);
  await page.getByRole('button',{name:'Bestätigen',exact:true}).click();
  await page.getByRole('navigation').getByRole('button',{name:'Übersicht',exact:true}).click();
  await page.getByRole('heading',{name:'Übersicht',exact:true}).waitFor();
  await page.getByRole('navigation').getByRole('button',{name:'Statistiken',exact:true}).click();
  await page.getByRole('heading',{name:'Umsatz & Kontozahlungen',exact:true}).waitFor();
  if(await page.locator('.chart svg').count()<5)throw new Error('Statistikdiagramme fehlen');
  await page.waitForFunction(()=>document.querySelectorAll('.recharts-bar-rectangle path').length>0,{},{timeout:10000}).catch(async error=>{console.log(await page.locator('.recharts-surface').first().evaluate(e=>({html:e.outerHTML.slice(0,2500),display:getComputedStyle(e).display,width:e.getBoundingClientRect().width,height:e.getBoundingClientRect().height})));throw error;});
  await page.getByRole('button',{name:'Letzte 3 Monate',exact:true}).click();
  await page.getByRole('heading',{name:'Umsatz & Kontozahlungen',exact:true}).waitFor();
  await page.waitForFunction(()=>document.querySelectorAll('.recharts-bar-rectangle path').length>0,{},{timeout:10000});
  await page.waitForFunction(()=>[...document.querySelectorAll('.chart svg[role="application"]')].every(e=>e.getBoundingClientRect().width>100),{},{timeout:5000});
  await page.locator('.chart').first().screenshot({path:resolve(directory,'chart-detail.png')});
  await page.screenshot({path:resolve(directory,'statistics.png'),fullPage:true});
  await page.setViewportSize({width:390,height:844});
  await page.waitForFunction(()=>document.documentElement.scrollWidth<=innerWidth,{},{timeout:5000});
  await page.screenshot({path:resolve(directory,'mobile.png'),fullPage:true});
  const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);if(overflow){console.log(await page.evaluate(()=>[...document.querySelectorAll('body *')].filter(e=>e.getBoundingClientRect().right>innerWidth+1).slice(0,12).map(e=>({tag:e.tagName,class:e.className,width:e.getBoundingClientRect().width,right:e.getBoundingClientRect().right}))));throw new Error('Mobile viewport overflows');}
  await page.getByRole('button',{name:'Abmelden',exact:true}).click();await page.getByRole('heading',{name:'Willkommen zurück'}).waitFor();
  if(errors.length)throw new Error(errors.join('\n'));
  console.log('Browserprüfung: MFA, acht Beispielmitglieder ohne E-Mail-Felder, Abrechnungen, Artikel, Testversand, E-Mail-Wechsel mit beiden Bestätigungen und erneuter MFA-Anmeldung, fünf Diagramme und Mobilansicht bestanden.');
}finally{
  await browser.close();
  const cleanup=new DatabaseSync(fileURLToPath(new URL('../../outputs/backoffice-preview/demo-auth.sqlite',import.meta.url)));
  cleanup.prepare("UPDATE bo_user SET email='browserqa@example.test' WHERE id=?").run(qaUser.id);
  cleanup.prepare('DELETE FROM bo_session WHERE "userId"=?').run(qaUser.id);cleanup.close();
}
