"use client";

import { useEffect, useState } from "react";
import { TabletNumberField } from "./TabletNumberField";

type Campaign={id:string;name:string;rewardType:"free_item"|"percent";rewardValue:number;rewardLabel:string;totalWins:number;remainingWins:number;claimedWins:number;startsAt:string;endsAt:string;status:string};
type Claim={id:string;campaignId:string;claimedAt:string;winnerName:string;rewardAmount:number;rewardLabel:string};
const localInput=(date:Date)=>new Date(date.getTime()-date.getTimezoneOffset()*60000).toISOString().slice(0,16);
const formatDate=(value:string)=>new Date(value).toLocaleString("de-DE",{day:"2-digit",month:"2-digit",year:"2-digit",hour:"2-digit",minute:"2-digit"});
const fetchRewards=async()=>{const response=await fetch("/api/random-rewards"),data=await response.json();if(!response.ok)throw new Error(data.error||"Glücksmomente konnten nicht geladen werden");return data as {now:string;campaigns:Campaign[];claims:Claim[]}};

export function RandomRewardsPanel(){
  const [campaigns,setCampaigns]=useState<Campaign[]>([]),[claims,setClaims]=useState<Claim[]>([]),[serverNow,setServerNow]=useState(0),[showForm,setShowForm]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState("");
  const [name,setName]=useState("Glücksmoment"),[rewardType,setRewardType]=useState<"free_item"|"percent">("free_item"),[rewardValue,setRewardValue]=useState<number|null>(20),[totalWins,setTotalWins]=useState<number|null>(3),[startsAt,setStartsAt]=useState(""),[endsAt,setEndsAt]=useState("");
  useEffect(()=>{let active=true;fetchRewards().then(data=>{if(!active)return;setCampaigns(data.campaigns||[]);setClaims(data.claims||[]);setServerNow(Date.parse(data.now))}).catch(reason=>{if(active)setError(reason instanceof Error?reason.message:"Glücksmomente konnten nicht geladen werden")});return()=>{active=false}},[]);
  const load=async()=>{const data=await fetchRewards();setCampaigns(data.campaigns||[]);setClaims(data.claims||[]);setServerNow(Date.parse(data.now))};
  const openForm=()=>{const start=new Date(Date.now()+5*60*1000),end=new Date(Date.now()+4*60*60*1000);setStartsAt(localInput(start));setEndsAt(localInput(end));setShowForm(true);setError("")};
  const reset=()=>{const start=new Date(Date.now()+5*60*1000),end=new Date(Date.now()+4*60*60*1000);setName("Glücksmoment");setRewardType("free_item");setRewardValue(20);setTotalWins(3);setStartsAt(localInput(start));setEndsAt(localInput(end));setError("");setShowForm(false)};
  const create=async()=>{setBusy(true);setError("");try{const response=await fetch("/api/random-rewards",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name,rewardType,rewardValue,totalWins,startsAt:new Date(startsAt).toISOString(),endsAt:new Date(endsAt).toISOString()})}),data=await response.json();if(!response.ok)throw new Error(data.error);reset();await load()}catch(reason){setError(reason instanceof Error?reason.message:"Aktion konnte nicht angelegt werden")}finally{setBusy(false)}};
  const cancel=async(campaign:Campaign)=>{if(!confirm(`„${campaign.name}“ wirklich vorzeitig beenden? Noch nicht vergebene Gewinne verfallen.`))return;setBusy(true);const response=await fetch("/api/random-rewards",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id:campaign.id,action:"cancel"})}),data=await response.json();if(!response.ok)setError(data.error||"Aktion konnte nicht beendet werden");else await load();setBusy(false)};
  const status=(campaign:Campaign)=>{if(campaign.status==="cancelled")return {label:"Beendet",kind:"cancelled"};if(!campaign.remainingWins)return {label:"Alle Gewinne verteilt",kind:"done"};if(serverNow<Date.parse(campaign.startsAt))return {label:"Geplant",kind:"planned"};if(serverNow>Date.parse(campaign.endsAt))return {label:"Abgelaufen",kind:"ended"};return {label:"Läuft jetzt",kind:"active"}};
  return <section className="rewards-admin">
    <div className="rewards-intro"><div className="reward-star">★</div><div><p className="eyebrow">ZUFÄLLIGE GEWINNE</p><h2>Glücksmomente</h2><p>Die App verteilt die festgelegten Gewinne unvorhersehbar über den Zeitraum. Zukünftige Gewinnzeitpunkte bleiben auch für den Admin verborgen.</p></div><button onClick={openForm}>+ Aktion anlegen</button></div>
    {showForm&&<div className="reward-form"><div className="reward-form-head"><div><p className="eyebrow">NEUE AKTION</p><h3>Gewinne vorbereiten</h3></div><button aria-label="Formular schließen" onClick={reset}>×</button></div><label>Name der Aktion<input autoFocus value={name} maxLength={80} onChange={event=>setName(event.target.value)} placeholder="z. B. Turnier-Glück"/></label><div className="reward-kind" aria-label="Gewinnart"><button className={rewardType==="free_item"?"active":""} onClick={()=>setRewardType("free_item")}><span>🥤</span><strong>Ein Artikel gratis</strong><small>Der günstigste Artikel des Einkaufs wird kostenlos.</small></button><button className={rewardType==="percent"?"active":""} onClick={()=>setRewardType("percent")}><span>%</span><strong>Besonderer Rabatt</strong><small>Der gesamte Einkauf wird prozentual günstiger.</small></button></div><div className="reward-fields"><label>Anzahl der Gewinne<TabletNumberField label="Anzahl der Gewinne" value={totalWins} onChange={setTotalWins} min={1} max={50}/></label>{rewardType==="percent"&&<label>Rabatt pro Gewinn<TabletNumberField label="Rabatt pro Gewinn" value={rewardValue} onChange={setRewardValue} min={1} max={100} step={5} unit="%"/></label>}<label>Beginn<input type="datetime-local" value={startsAt} onChange={event=>setStartsAt(event.target.value)}/></label><label>Ende<input type="datetime-local" value={endsAt} onChange={event=>setEndsAt(event.target.value)}/></label></div><div className="reward-safety"><span>🔒</span><div><strong>Manipulationsgeschützt</strong><small>Pro Einkauf gibt es höchstens einen Gewinn. Die Zeitpunkte werden sicher auf dem Server erzeugt und nicht angezeigt.</small></div></div>{error&&<p className="reward-error">{error}</p>}<button className="reward-create" disabled={busy||name.trim().length<3||!totalWins||!startsAt||!endsAt} onClick={create}>{busy?"Wird sicher vorbereitet …":`${totalWins||0} Glücksmomente anlegen`}</button></div>}
    {!showForm&&error&&<p className="reward-error">{error}</p>}
    <div className="reward-campaigns">{campaigns.map(campaign=>{const state=status(campaign),percent=Math.round(campaign.claimedWins/campaign.totalWins*100);return <article className={state.kind} key={campaign.id}><div className="reward-card-head"><div><span className={`reward-status ${state.kind}`}>{state.label}</span><h3>{campaign.name}</h3><small>{formatDate(campaign.startsAt)} – {formatDate(campaign.endsAt)}</small></div><strong>{campaign.rewardLabel}</strong></div><div className="reward-progress"><div><i style={{width:`${percent}%`}}/></div><span><b>{campaign.claimedWins}</b> von {campaign.totalWins} vergeben · {campaign.remainingWins} übrig</span></div>{campaign.status==="active"&&campaign.remainingWins>0&&Date.parse(campaign.endsAt)>serverNow&&<button className="reward-cancel" disabled={busy} onClick={()=>cancel(campaign)}>Aktion beenden</button>}</article>})}{!campaigns.length&&<div className="reward-empty"><span>☆</span><strong>Noch keine Glücksmomente angelegt</strong><small>Lege zum Beispiel drei Freigetränke für den nächsten Vereinsabend fest.</small></div>}</div>
    {claims.length>0&&<div className="reward-history"><div><p className="eyebrow">BEREITS VERLOST</p><h3>Letzte Gewinner</h3></div>{claims.slice(0,10).map(claim=><div key={claim.id}><span>★</span><strong>{claim.winnerName}</strong><small>{claim.rewardLabel} · {formatDate(claim.claimedAt)}</small><b>−{claim.rewardAmount.toLocaleString("de-DE",{style:"currency",currency:"EUR"})}</b></div>)}</div>}
  </section>;
}
