import { env } from "cloudflare:workers";
import { requireRole } from "../session";
import { requireProfile } from "../profile-session";

type PersonRow={memberId:string;memberName:string;openingBalance:number;charges:number;payments:number;adjustments:number;closingBalance:number;currentBalance:number};
type ItemRow={memberId:string;productName:string;quantity:number;total:number};
const esc=(v:unknown)=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]!));
const eur=(n:number)=>Number(n||0).toLocaleString("de-DE",{style:"currency",currency:"EUR"});
const monthLabel=(month:string)=>new Date(`${month}-01T12:00:00Z`).toLocaleDateString("de-DE",{month:"long",year:"numeric"});

export async function GET(request:Request){
  const [user,profile]=await Promise.all([requireRole(request,["Kassendienst","Vorstand"]),requireProfile(request)]);if(!user||!profile)return Response.json({error:"Keine Berechtigung oder Profilanmeldung abgelaufen"},{status:403});
  const url=new URL(request.url),month=url.searchParams.get("month")||new Date().toISOString().slice(0,7);if(!/^\d{4}-(0[1-9]|1[0-2])$/.test(month))return Response.json({error:"Ungültiger Monat"},{status:400});
  const start=`${month}-01T00:00:00.000Z`,nextDate=new Date(`${month}-01T00:00:00.000Z`);nextDate.setUTCMonth(nextDate.getUTCMonth()+1);const end=nextDate.toISOString();
  const [activity,opening,current,items,products]=await Promise.all([
    env.DB.prepare("SELECT member_id memberId,MAX(member_name) memberName,ROUND(SUM(CASE WHEN amount>0 THEN amount ELSE 0 END),2) charges,ROUND(ABS(SUM(CASE WHEN type='Zahlung' THEN amount ELSE 0 END)),2) payments,ROUND(SUM(CASE WHEN amount<0 AND type<>'Zahlung' THEN amount ELSE 0 END),2) adjustments,ROUND(SUM(amount),2) net FROM account_transactions WHERE profile_id=? AND created_at>=? AND created_at<? GROUP BY member_id ORDER BY memberName").bind(profile.id,start,end).all<Record<string,unknown>>(),
    env.DB.prepare("SELECT member_id memberId,MAX(member_name) memberName,ROUND(SUM(amount),2) balance FROM account_transactions WHERE profile_id=? AND created_at<? GROUP BY member_id").bind(profile.id,start).all<Record<string,unknown>>(),
    env.DB.prepare("SELECT member_id memberId,MAX(member_name) memberName,ROUND(SUM(amount),2) balance FROM account_transactions WHERE profile_id=? GROUP BY member_id").bind(profile.id).all<Record<string,unknown>>(),
    env.DB.prepare("SELECT at.member_id memberId,si.product_name productName,SUM(si.quantity) quantity,ROUND(SUM(si.total),2) total FROM account_transactions at JOIN sale_items si ON si.sale_id=at.sale_id LEFT JOIN reversals r ON r.sale_id=at.sale_id WHERE at.profile_id=? AND at.created_at>=? AND at.created_at<? AND at.amount>0 AND r.id IS NULL GROUP BY at.member_id,si.product_name ORDER BY at.member_id,quantity DESC").bind(profile.id,start,end).all<ItemRow>(),
    env.DB.prepare("SELECT si.product_name productName,SUM(si.quantity) quantity,ROUND(SUM(si.total),2) total FROM sale_items si JOIN sales s ON s.id=si.sale_id LEFT JOIN reversals r ON r.sale_id=s.id WHERE s.profile_id=? AND s.time>=? AND s.time<? AND r.id IS NULL AND si.counts_for_consumption=1 GROUP BY si.product_name ORDER BY quantity DESC").bind(profile.id,start,end).all<Record<string,unknown>>()
  ]);
  const openingMap=new Map(opening.results.map(r=>[String(r.memberId),r])),currentMap=new Map(current.results.map(r=>[String(r.memberId),r])),activityMap=new Map(activity.results.map(r=>[String(r.memberId),r]));const ids=[...new Set([...activityMap.keys(),...opening.results.filter(r=>Math.abs(Number(r.balance||0))>.001).map(r=>String(r.memberId))])];
  const people:PersonRow[]=ids.map(id=>{const r=activityMap.get(id),openRow=openingMap.get(id),open=Number(openRow?.balance||0),net=Number(r?.net||0),cur=currentMap.get(id);return {memberId:id,memberName:String(r?.memberName||cur?.memberName||openRow?.memberName||id),openingBalance:open,charges:Number(r?.charges||0),payments:Number(r?.payments||0),adjustments:Number(r?.adjustments||0),closingBalance:Math.round((open+net)*100)/100,currentBalance:Number(cur?.balance||0)}}).sort((a,b)=>a.memberName.localeCompare(b.memberName,"de"));
  const payload={month,label:monthLabel(month),people,items:items.results,products:products.results.map(r=>({productName:String(r.productName),quantity:Number(r.quantity),total:Number(r.total)})),summary:{charges:people.reduce((s,p)=>s+p.charges,0),payments:people.reduce((s,p)=>s+p.payments,0),people:people.length}};
  const memberId=url.searchParams.get("memberId");if(!memberId)return Response.json(payload,{headers:{"cache-control":"no-store"}});
  const person=people.find(p=>p.memberId===memberId);if(!person)return Response.json({error:"Für diese Person gibt es im gewählten Monat keine Abrechnung"},{status:404});const personItems=items.results.filter(i=>i.memberId===memberId);const rows=personItems.map(i=>`<tr><td>${esc(i.quantity)}× ${esc(i.productName)}${Number(i.total)===0?" <small>(im Paket enthalten)</small>":""}</td><td>${Number(i.total)===0?"inklusive":eur(i.total)}</td></tr>`).join("");
  const html=`<!doctype html><html lang="de"><meta charset="utf-8"><title>Monatsabrechnung ${esc(person.memberName)} · ${esc(payload.label)}</title><style>body{font:15px Arial;max-width:720px;margin:30px auto;padding:24px;color:#172b25}h1{margin-bottom:4px}.meta{color:#68766f}table{width:100%;border-collapse:collapse;margin:22px 0}th,td{text-align:left;padding:10px;border-bottom:1px solid #ddd}th:last-child,td:last-child{text-align:right}.totals{margin-left:auto;width:min(360px,100%)}.totals div{display:flex;justify-content:space-between;padding:8px}.due{font-size:20px;font-weight:bold;border-top:2px solid #173b32}.note{font-size:12px;color:#68766f;margin-top:25px}@media print{button{display:none}body{margin:0}}</style><h1>Monatsabrechnung</h1><p class="meta">${esc(profile.name)} · ${esc(payload.label)}<br>${esc(person.memberName)} · ${esc(person.memberId)}</p><h2>Getränke und Artikel</h2><table><thead><tr><th>Artikel</th><th>Betrag</th></tr></thead><tbody>${rows||"<tr><td>Keine einzelnen Artikel vorhanden</td><td>–</td></tr>"}</tbody></table><div class="totals"><div><span>Stand Monatsanfang</span><b>${eur(person.openingBalance)}</b></div><div><span>Neue Buchungen</span><b>${eur(person.charges)}</b></div><div><span>Zahlungen</span><b>− ${eur(person.payments)}</b></div>${person.adjustments?`<div><span>Korrekturen/Storno</span><b>${eur(person.adjustments)}</b></div>`:""}<div class="due"><span>Stand Monatsende</span><b>${eur(person.closingBalance)}</b></div></div><p class="note">Digital erzeugte Vereinsabrechnung. Der aktuelle Gesamtsaldo kann durch spätere Buchungen vom Monatsendstand abweichen.</p><button onclick="print()">Abrechnung drucken</button></html>`;return new Response(html,{headers:{"content-type":"text/html; charset=utf-8","cache-control":"no-store"}});
}
