import { env } from "cloudflare:workers";
import { requireRole } from "../session";
import { hashProfilePin,normalizeRecoveryCard,randomRecoveryCard,randomSalt,recoveryCardSlot,requireProfile } from "../profile-session";

type StoredCard={slot:number;salt:string;hash:string};
const safeEqual=(left:string,right:string)=>{if(left.length!==right.length)return false;let difference=0;for(let index=0;index<left.length;index++)difference|=left.charCodeAt(index)^right.charCodeAt(index);return difference===0};
const makeCards=async()=>{const cards=[1,2,3].map(slot=>({slot,code:randomRecoveryCard(slot),salt:randomSalt()}));return Promise.all(cards.map(async card=>({...card,hash:await hashProfilePin(normalizeRecoveryCard(card.code),card.salt)})))};

export async function PUT(request:Request){
  try{
    const [admin,profile]=await Promise.all([requireRole(request,["Vorstand"]),requireProfile(request)]);if(!admin||!profile)return Response.json({error:"Vorstand und Profilanmeldung erforderlich"},{status:403});const now=new Date().toISOString(),cards=await makeCards();
    await env.DB.batch([env.DB.prepare("UPDATE profile_recovery_keys SET used_at=? WHERE profile_id=? AND used_at IS NULL").bind(now,profile.id),...cards.map(card=>env.DB.prepare("INSERT INTO profile_recovery_keys (id,profile_id,slot,salt,hash,created_at) VALUES (?,?,?,?,?,?)").bind(crypto.randomUUID(),profile.id,card.slot,card.salt,card.hash,now)),env.DB.prepare("UPDATE profiles SET recovery_failed_attempts=0,recovery_locked_until=NULL,updated_at=? WHERE id=?").bind(now,profile.id),env.DB.prepare("INSERT INTO audit_logs (id,action,entity_type,entity_id,operator_id,details_json,created_at) VALUES (?,?,?,?,?,?,?)").bind(crypto.randomUUID(),"PROFILE_RECOVERY_CARDS_ISSUED","profile",profile.id,admin.id,JSON.stringify({scheme:"2-of-3",count:3}),now)]);
    await env.BACKUPS.put(`security/${profile.id}/${now.slice(0,10)}/recovery-cards-${crypto.randomUUID()}.json`,JSON.stringify({profileId:profile.id,action:"PROFILE_RECOVERY_CARDS_ISSUED",issuedBy:{id:admin.id,name:admin.name},scheme:"2-of-3",createdAt:now}),{httpMetadata:{contentType:"application/json"}});
    return Response.json({ok:true,recoveryCards:cards.map(card=>({slot:card.slot,code:card.code}))});
  }catch(error){return Response.json({error:error instanceof Error?error.message:"Notfallkarten konnten nicht erzeugt werden"},{status:500})}
}

export async function POST(request:Request){
  try{
    const body=await request.json() as {profileId?:string;cards?:string[];newPin?:string};const entered=(body.cards||[]).map(normalizeRecoveryCard),slots=entered.map(recoveryCardSlot);if(!body.profileId||entered.length!==2||entered.some(code=>code.length!==17)||slots.some(slot=>slot<1)||new Set(slots).size!==2)return Response.json({error:"Bitte zwei unterschiedliche vollständige Notfallkarten eingeben"},{status:400});if(!/^[0-9]{6}$/.test(body.newPin||""))return Response.json({error:"Die neue PIN muss genau sechs Ziffern haben"},{status:400});
    const nowDate=new Date(),now=nowDate.toISOString(),profile=await env.DB.prepare("SELECT id,name,recovery_failed_attempts recoveryFailedAttempts,recovery_locked_until recoveryLockedUntil FROM profiles WHERE id=? AND active=1").bind(body.profileId).first<{id:string;name:string;recoveryFailedAttempts:number;recoveryLockedUntil:string|null}>();if(!profile)return Response.json({error:"Wiederherstellung nicht möglich"},{status:403});if(profile.recoveryLockedUntil&&profile.recoveryLockedUntil>now)return Response.json({error:"Die Wiederherstellung ist nach mehreren Fehlversuchen 15 Minuten gesperrt."},{status:429});
    const rows=await env.DB.prepare("SELECT slot,salt,hash FROM profile_recovery_keys WHERE profile_id=? AND used_at IS NULL ORDER BY slot").bind(profile.id).all<StoredCard>(),bySlot=new Map(rows.results.map(card=>[card.slot,card]));let valid=rows.results.length===3;for(let index=0;index<entered.length;index++){const stored=bySlot.get(slots[index]);if(!stored){valid=false;continue}const calculated=await hashProfilePin(entered[index],stored.salt);if(!safeEqual(calculated,stored.hash))valid=false}
    if(!valid){const attempts=Number(profile.recoveryFailedAttempts||0)+1,locked=attempts>=5?new Date(nowDate.getTime()+15*60*1000).toISOString():null;await env.DB.prepare("UPDATE profiles SET recovery_failed_attempts=?,recovery_locked_until=? WHERE id=?").bind(locked?0:attempts,locked,profile.id).run();return Response.json({error:locked?"Zu viele Fehlversuche. Die Wiederherstellung ist 15 Minuten gesperrt.":`Notfallkarten sind ungültig · noch ${5-attempts} Versuche`},{status:403})}
    const pinSalt=randomSalt(),pinHash=await hashProfilePin(body.newPin!,pinSalt),auditId=crypto.randomUUID();await env.DB.batch([env.DB.prepare("UPDATE profiles SET pin_salt=?,pin_hash=?,must_change_pin=0,failed_attempts=0,locked_until=NULL,recovery_failed_attempts=0,recovery_locked_until=NULL,updated_at=? WHERE id=?").bind(pinSalt,pinHash,now,profile.id),env.DB.prepare("UPDATE profile_recovery_keys SET used_at=? WHERE profile_id=? AND used_at IS NULL").bind(now,profile.id),env.DB.prepare("DELETE FROM profile_sessions WHERE profile_id=?").bind(profile.id),env.DB.prepare("INSERT INTO audit_logs (id,action,entity_type,entity_id,operator_id,details_json,created_at) VALUES (?,?,?,?,?,?,?)").bind(auditId,"PROFILE_PIN_RECOVERED","profile",profile.id,"RECOVERY_2_OF_3",JSON.stringify({scheme:"2-of-3",usedSlots:slots.sort(),newCardsRequired:true}),now)]);
    await env.BACKUPS.put(`security/${profile.id}/${now.slice(0,10)}/pin-recovered-${auditId}.json`,JSON.stringify({profileId:profile.id,action:"PROFILE_PIN_RECOVERED",scheme:"2-of-3",usedSlots:slots.sort(),newCardsRequired:true,createdAt:now}),{httpMetadata:{contentType:"application/json"}});return Response.json({ok:true,newCardsRequired:true});
  }catch(error){return Response.json({error:error instanceof Error?error.message:"PIN konnte nicht wiederhergestellt werden"},{status:500})}
}
